name: agenthq_mobile
description: AgentHQ Mobile Client - AI-powered workspace automation
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Networking
  dio: ^5.4.0

  # Authentication
  google_sign_in: ^6.2.1

  # Storage
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

  # Connectivity
  connectivity_plus: ^5.0.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  # UI & Utils
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  go_router: ^12.1.3

  # Icons
  cupertino_icons: ^1.0.6

  # JSON Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - images/

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

# Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0F0F0F"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

# Native Splash Screen
flutter_native_splash:
  color: "#0F0F0F"
  image: assets/splash/splash_logo.png
  android: true
  ios: true
